import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
if (process.platform !== 'darwin') throw new Error('This installer supports macOS only.');
const home = process.env.ORACLE_REPO_MCP_HOME ?? path.join(os.homedir(), 'Library/Application Support/Oracle Repo MCP');
const bin = path.join(home, 'bin');
await fs.mkdir(bin, {recursive:true,mode:0o700});
const temp = await fs.mkdtemp(path.join(bin, '.install-'));
const get = async url => {const r=await fetch(url); if(!r.ok) throw new Error(`Download failed (${r.status})`); return r;};
try {
  const release = await (await get('https://api.github.com/repos/openai/tunnel-client/releases/latest')).json();
  const arch = process.arch === 'arm64' ? 'arm64' : process.arch === 'x64' ? 'amd64' : null;
  if (!arch) throw new Error('Unsupported macOS architecture.');
  const name = `tunnel-client-${release.tag_name}-darwin-${arch}.zip`;
  const asset = release.assets.find(a => a.name === name);
  const sumsAsset = release.assets.find(a => a.name === 'SHA256SUMS.txt');
  if (!asset || !sumsAsset) throw new Error('The official release lacks the required asset/checksum.');
  const sums = await (await get(sumsAsset.browser_download_url)).text();
  const entry = sums.split('\n').find(line => line.trim().split(/\s+/).at(-1)?.replace(/^\*/, '') === name);
  const expected = entry?.trim().split(/\s+/)[0];
  if (!expected || !/^[a-f0-9]{64}$/i.test(expected)) throw new Error('No valid official checksum.');
  const data = Buffer.from(await (await get(asset.browser_download_url)).arrayBuffer());
  const actual = createHash('sha256').update(data).digest('hex');
  if (actual !== expected) throw new Error('Official checksum mismatch; nothing installed.');
  const zip = path.join(temp, 'release.zip');
  await fs.writeFile(zip, data, {mode:0o600});
  execFileSync('/usr/bin/unzip', ['-q', '-j', zip, 'tunnel-client', '-d', temp]);
  await fs.chmod(path.join(temp, 'tunnel-client'), 0o700);
  await fs.rename(path.join(temp, 'tunnel-client'), path.join(bin, 'tunnel-client'));
  await fs.writeFile(path.join(bin, 'tunnel-client-release.json'), JSON.stringify({version:release.tag_name,asset:name,sha256:actual,source:asset.browser_download_url},null,2)+'\n',{mode:0o600});
  console.log(JSON.stringify({installed:path.join(bin,'tunnel-client'),version:release.tag_name,checksum_verified:true}));
} finally {await fs.rm(temp,{recursive:true,force:true});}
