/** One source for helper guidance and the corresponding validation errors. */
export const rules = Object.freeze({
  page: { title: 'title is required; layout must be article, wide, or canvas.', recommendation: 'at most one recommendation is allowed' },
  section: { id: 'id must be a lowercase slug; title is required.' },
  readingColumn: { children: 'children are required; text and helper output stay at article width.' },
  callout: { variant: 'variant must be note, warn, or danger; body is required.' },
  calloutStack: { items: 'items must be a non-empty array of callouts.' },
  recommendation: { lead: 'lead is required; a page allows at most one recommendation.' },
  quote: { text: 'text is required; attribution is optional.' },
  disclosure: { summary: 'summary is required; children are the expandable detail.' },
  stats: { count: 'use two to five tiles', value: 'each tile needs a value.', label: 'each tile needs a label.', source: 'source is required for the supplied numbers; use "illustrative" only for examples.' },
  table: { data: 'columns and rows must each be non-empty arrays; object rows use column keys or plain-text labels.' },
  bars: { source: 'source is required; values must be non-negative.' },
  line: { source: 'source is required; points must be ordered label/value pairs.' },
  stacked: { source: 'source is required; series names must match numeric segments.' },
  sparkline: { source: 'source and visible value text are required.' },
  steps: { count: 'use two to six stages, each with a title.' },
  timeline: { count: 'use at most 12 ordered events; computed diagrams also require a text summary.' },
  finding: { severity: 'severity must be high, medium, or low; title is required.' },
  findings: { items: 'items must be finding() results or finding field objects.' },
  fileMap: { path: 'each item needs a path.', role: 'each item needs a role.' },
  comparison: { count: 'use two to four options', columns: 'option count must match columns', recommendation: 'mark at most one option as recommended.' },
  code: { source: 'source is required; use html`` for trusted highlighting.' },
  diff: { lines: 'lines must be non-empty; each operation is +, -, or space.' },
  figure: { visual: 'provide src with alt or svg with label.' },
  gallery: { count: 'use two to four items', visual: 'each item needs src with alt or svg with label.' },
  flowDiagram: { summary: 'viewBox and SVG content are required; caption or notes is required as the accessible description; emphasize at most two nodes.' },
  flow: { nodes: 'use at most 12 nodes with unique IDs; edges must refer to those nodes; summary is required; emphasize at most two nodes; use a table for larger graphs.' },
  state: { nodes: 'use at most 12 states with unique IDs; transitions must refer to those states; summary is required; emphasize at most two states.' },
  sequence: { actors: 'use at most 12 actors; events must refer to those actors; summary is required.' },
  mockup: { caption: 'label and caption are required; describe this as a concept, not observed UI.' },
});
export const ruleDescriptions = (helper) => Object.values(rules[helper] ?? {}).join(' ');
