import { Registry } from '../../../core/src/registry.js';
import { s, id, sha, check } from '../../../protocol/src/index.js';
import type { CapabilityContext } from '../../../core/src/types.js';
export function addTasks(r: Registry) {
    const add = (name: string, description: string, input: any, effect: 'read' | 'write', handler: any) => r.add({ id: 'tasks.' + name, description, input, effect, family: 'tasks', handler });
    const task = (c: CapabilityContext, id: string) => { const t = c.store.one('SELECT * FROM tasks WHERE id=? AND workspace_id=?', id, c.workspace.id); check(t, 'NOT_FOUND', 'Task not found in workspace'); return t; };
    add('create', 'Create an optional task; never required before file or command work.', s.object({ label: s.string(200), brief: s.string(65536) }, ['label']), 'write', (c: CapabilityContext, a: any) => { const taskId = id('task'); c.store.run('INSERT INTO tasks VALUES(?,?,?,?,?,?,?)', taskId, c.workspace.id, a.label, a.brief ?? '', '[]', 'open', Date.now()); return { taskId, label: a.label }; });
    add('update_plan', 'Store user/model-provided steps. Does not call a model.', s.object({ taskId: s.key(), steps: s.array(s.object({ text: s.string(4000), state: s.enum('pending', 'active', 'done') }), 100) }), 'write', (c: CapabilityContext, a: any) => { const t = task(c, a.taskId); check(t.state === 'open', 'FORBIDDEN', 'Task is closed'); c.store.run('UPDATE tasks SET plan=? WHERE id=?', JSON.stringify(a.steps), t.id); return { taskId: t.id, steps: a.steps }; });
    add('read', 'Read a task and its immutable report versions.', s.object({ taskId: s.key() }), 'read', (c: CapabilityContext, a: any) => { const t = task(c, a.taskId); return { taskId: t.id, label: t.label, brief: t.brief, plan: JSON.parse(t.plan), state: t.state, results: c.store.all('SELECT version,body,sha256,created_at FROM task_results WHERE task_id=? ORDER BY version', t.id) }; });
    add('save_result', 'Append an immutable final-report version; existing reports are never overwritten.', s.object({ taskId: s.key(), body: s.string(65536) }), 'write', (c: CapabilityContext, a: any) => { const t = task(c, a.taskId); const version = 1 + (c.store.one('SELECT MAX(version) v FROM task_results WHERE task_id=?', t.id)?.v ?? 0), hash = sha(a.body); c.store.run('INSERT INTO task_results VALUES(?,?,?,?,?)', t.id, version, a.body, hash, Date.now()); return { taskId: t.id, version, sha256: hash }; });
    add('close', 'Close only this task, preserving all reports and other jobs.', s.object({ taskId: s.key() }), 'write', (c: CapabilityContext, a: any) => { const t = task(c, a.taskId); c.store.run("UPDATE tasks SET state='closed' WHERE id=?", t.id); return { taskId: t.id, closed: true, jobsUnaffected: true }; });
}
