// Generated input contracts. Runtime examples use portal.family.method.
export interface CapabilityCalls {
  "artifacts.get"(args: { "artifactId": string; "cursor"?: string | null; "maxBytes"?: number }): Promise<{  }>;
  "code.run"(args: { "code": string; "capabilityIds": Array<string>; "limits"?: { "wallMs"?: number; "maxCalls"?: number } } & { stepKey: string }): Promise<{  }>;
  "code.run_read"(args: { "code": string; "capabilityIds": Array<string>; "limits"?: { "wallMs"?: number; "maxCalls"?: number } } & { stepKey: string }): Promise<{  }>;
  "documents.docx.create"(args: { "outputPath": string; "expectedOutputSha256": string | null; "markdown"?: string; "paragraphs"?: Array<{ "text": string; "style"?: "Normal" | "Heading1" | "Heading2" | "Heading3" | "Heading4" | "Heading5" | "Heading6" }>; "tables"?: Array<Array<Array<string>>> } & { stepKey: string }): Promise<{  }>;
  "documents.docx.edit"(args: { "path": string; "expectedSha256": string; "outputPath": string; "expectedOutputSha256": string | null; "edits": Array<{ "locator": string; "oldText": string; "newText": string; "expectedReplacements"?: number }> } & { stepKey: string }): Promise<{  }>;
  "documents.docx.inspect"(args: { "path": string; "expectedSha256"?: string }): Promise<{  }>;
  "documents.docx.read"(args: { "path": string; "expectedSha256"?: string; "offset"?: number; "limit"?: number }): Promise<{  }>;
  "documents.pdf.create"(args: { "outputPath": string; "expectedOutputSha256": string | null; "markdown": string } & { stepKey: string }): Promise<{  }>;
  "documents.pdf.edit"(args: { "path": string; "expectedSha256": string; "outputPath": string; "expectedOutputSha256": string | null; "additionalSources"?: Array<{ "path": string; "expectedSha256": string }>; "pages": Array<{ "source"?: number; "page": number }> } & { stepKey: string }): Promise<{  }>;
  "documents.pdf.inspect"(args: { "path": string; "expectedSha256"?: string }): Promise<{  }>;
  "documents.pdf.read"(args: { "path": string; "expectedSha256"?: string; "startPage"?: number; "maxPages"?: number }): Promise<{  }>;
  "documents.pdf.render"(args: { "path": string; "expectedSha256"?: string; "page": number; "maxEdge"?: number }): Promise<{  }>;
  "documents.sheet.create"(args: { "outputPath": string; "expectedOutputSha256": string | null; "sheets": Array<{ "name": string; "cells"?: Array<{ "cell": string; "value"?: string | number | boolean | null; "formula"?: string; "styleId"?: number; "format"?: { "bold"?: boolean; "numberFormat"?: string } }> }> } & { stepKey: string }): Promise<{  }>;
  "documents.sheet.edit"(args: { "path": string; "expectedSha256": string; "outputPath": string; "expectedOutputSha256": string | null; "sheet": string; "cells": Array<{ "cell": string; "value"?: string | number | boolean | null; "formula"?: string; "styleId"?: number; "format"?: { "bold"?: boolean; "numberFormat"?: string } }> } & { stepKey: string }): Promise<{  }>;
  "documents.sheet.inspect"(args: { "path": string; "expectedSha256"?: string }): Promise<{  }>;
  "documents.sheet.legacy_read"(args: { "path": string; "expectedSha256"?: string }): Promise<{  }>;
  "documents.sheet.read"(args: { "path": string; "expectedSha256"?: string; "sheet": string; "range"?: string }): Promise<{  }>;
  "documents.sheet.xlsm_edit"(args: { "path": string; "expectedSha256"?: string } & { stepKey: string }): Promise<{  }>;
  "files.append"(args: { "path": string; "text": string; "expectedSha256": string | null } & { stepKey: string }): Promise<{  }>;
  "files.apply_patch"(args: { "patch": string; "expectedSha256": { ; [key:string]: string | null } } & { stepKey: string }): Promise<{  }>;
  "files.copy"(args: { "source": string; "destination": string; "expectedSourceSha256": string; "expectedDestinationSha256": string | null; "recursive"?: boolean } & { stepKey: string }): Promise<{  }>;
  "files.list"(args: { "path": string; "cursor"?: string | null; "limit"?: number; "hidden"?: boolean }): Promise<{  }>;
  "files.manifest"(args: { "path": string }): Promise<{  }>;
  "files.mkdir"(args: { "path": string; "recursive"?: boolean; "expectedAbsent": unknown } & { stepKey: string }): Promise<{  }>;
  "files.move"(args: { "source": string; "destination": string; "expectedSourceSha256": string; "expectedDestinationSha256": string | null; "recursive"?: boolean } & { stepKey: string }): Promise<{  }>;
  "files.read"(args: { "path": string; "startLine"?: number; "maxLines"?: number; "startByte"?: number; "maxBytes"?: number; "tailLines"?: number; "expectedSha256"?: string }): Promise<{  }>;
  "files.read_many"(args: { "files": Array<{ "path": string; "startLine"?: number; "maxLines"?: number; "startByte"?: number; "maxBytes"?: number; "tailLines"?: number; "expectedSha256"?: string }> }): Promise<{  }>;
  "files.remove"(args: { "path": string; "expectedSha256": string; "recursive"?: boolean } & { stepKey: string }): Promise<{  }>;
  "files.replace"(args: { "path": string; "expectedSha256": string; "oldText": string; "newText": string; "expectedReplacements": number } & { stepKey: string }): Promise<{  }>;
  "files.stage_chunk"(args: { "uploadId": string; "offset": number; "base64": string; "sha256": string } & { stepKey: string }): Promise<{  }>;
  "files.stage_commit"(args: { "uploadId": string } & { stepKey: string }): Promise<{  }>;
  "files.stage_start"(args: { "path": string; "expectedSha256": string | null; "outputSha256": string; "totalBytes": number } & { stepKey: string }): Promise<{  }>;
  "files.stat"(args: { "path": string }): Promise<{  }>;
  "files.tail"(args: { "path": string; "tailLines": number; "expectedSha256"?: string }): Promise<{  }>;
  "files.write"(args: { "path": string; "text": string; "expectedSha256": string | null } & { stepKey: string }): Promise<{  }>;
  "images.inspect"(args: { "path"?: string; "artifactId"?: string; "expectedSha256"?: string; "maxEdge"?: number; "crop"?: { "x": number; "y": number; "width": number; "height": number } }): Promise<{  }>;
  "images.view"(args: { "path"?: string; "artifactId"?: string; "expectedSha256"?: string; "maxEdge"?: number; "crop"?: { "x": number; "y": number; "width": number; "height": number } }): Promise<{  }>;
  "instructions.read_for_path"(args: { "path": string }): Promise<{  }>;
  "jobs.cancel"(args: { "jobId": string } & { stepKey: string }): Promise<{  }>;
  "jobs.get"(args: { "jobId": string }): Promise<{  }>;
  "jobs.list"(args: {  }): Promise<{  }>;
  "jobs.output"(args: { "jobId": string; "cursor"?: string | null; "maxBytes"?: number; "waitMs"?: number }): Promise<{  }>;
  "network.fetch"(args: { "url": string; "maxBytes"?: number } & { stepKey: string }): Promise<{  }>;
  "processes.list"(args: {  }): Promise<{  }>;
  "processes.signal"(args: { "pid": number; "startIdentity": string; "uid": number; "signal": "SIGTERM" | "SIGINT" } & { stepKey: string }): Promise<{  }>;
  "search.cancel"(args: { "searchId": string } & { stepKey: string }): Promise<{  }>;
  "search.list"(args: {  }): Promise<{  }>;
  "search.read"(args: { "searchId": string; "cursor"?: string | null; "maxResults"?: number; "waitMs"?: number }): Promise<{  }>;
  "search.start"(args: { "path": string; "pattern": string; "kind": "filename" | "literal" | "regex"; "fileGlob"?: string; "caseSensitive"?: boolean; "contextLines"?: number; "hidden"?: boolean; "respectIgnore"?: boolean; "documents"?: boolean; "maxResults"?: number }): Promise<{  }>;
  "tasks.close"(args: { "taskId": string } & { stepKey: string }): Promise<{  }>;
  "tasks.create"(args: { "label": string; "brief"?: string } & { stepKey: string }): Promise<{  }>;
  "tasks.read"(args: { "taskId": string }): Promise<{  }>;
  "tasks.save_result"(args: { "taskId": string; "body": string } & { stepKey: string }): Promise<{  }>;
  "tasks.update_plan"(args: { "taskId": string; "steps": Array<{ "text": string; "state": "pending" | "active" | "done" }> } & { stepKey: string }): Promise<{  }>;
  "terminal.exec"(args: { "argv": Array<string>; "cwd": string; "executionAccess"?: "inherit" | "read"; "tty"?: boolean; "rows"?: number; "cols"?: number; "env"?: { ; [key:string]: string }; "timeoutMs"?: number; "yieldMs"?: number } & { stepKey: string }): Promise<{  }>;
  "terminal.resize"(args: { "jobId": string; "rows": number; "cols": number } & { stepKey: string }): Promise<{  }>;
  "terminal.stdin"(args: { "jobId": string; "text"?: string; "base64"?: string; "closeStdin"?: boolean } & { stepKey: string }): Promise<{  }>;
}
